### ISSUE TITLE
Helm chart leverages deprecated machine CRD

### ISSUE THREAD

**Issue by philwelz** [Azure/gpu-provisioner#119]
The machine CRD installed with the gpu-provisioner Helm Chart is deprecated since [Karpenter v0.33.0](https://github.com/kubernetes-sigs/karpenter/releases/tag/v0.33.0).

It would be good that the gpu-provisioner would be adopted to the `karpenter.sh/v1beta1` APIs.

**Comment by helayoty** [comment]
duplicate with https://github.com/Azure/kaito/issues/339
